spring:
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/hybridb"
    username: "postgres"
    password: "123"
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
app:
  rentPeriodInDays: 7
  cronExpression : "0 0 10 ? * MON,TUE,WED,THU,FRI"