CREATE TABLE IF NOT EXISTS USERS(
    ID BIGSERIAL,
    FIRSTNAME VARCHAR(255) NOT NULL,
    LASTNAME VARCHAR(255) NOT NULL,
    USERNAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    CONSTRAINT USERS_PK_ID PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ROLES(
    ID BIGSERIAL,
    NAME VARCHAR(255) NOT NULL,
    CONSTRAINT ROLES_PK_ID PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS USER_ROLES(
    USER_ID BIGINT NOT NULL REFERENCES USERS(ID) ,
    ROLE_iD BIGINT NOT NULL REFERENCES ROLES(ID)
);

CREATE TABLE IF NOT EXISTS BOOKS(
    ID BIGSERIAL,
    AUTHOR VARCHAR(255) NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    AVAILABLE_COPIES INTEGER NOT NULL,
    TOTAL_COPIES INTEGER NOT NULL,
    CONSTRAINT BOOKS_PK_ID PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS RENTS(
    ID BIGSERIAL,
    RENT_DATE TIMESTAMP NOT NULL,
    BOOK_ID BIGINT NOT NULL REFERENCES BOOKS(ID),
    USER_ID BIGINT NOT NULL REFERENCES USERS(ID),
    CONSTRAINT RENTS_PK_ID PRIMARY KEY (id)
);