CREATE TABLE USERS(
    ID BIGINT NOT NULL,
    FIRSTNAME VARCHAR(255) NOT NULL,
    LASTNAME VARCHAR(255) NOT NULL,
    USERNAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE ROLES(
    ID BIGINT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE USER_ROLES(
    USER_ID BIGINT NOT NULL,
    ROLE_iD BIGINT NOT NULL,
);

CREATE TABLE BOOKS(
    ID BIGINT NOT NULL,
    AUTHOR VARCHAR(255) NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    AVAILABLE_COPIES INTEGER NOT NULL,
    TOTAL_COPIES INTEGER NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE RENTS(
    ID BIGINT NOT NULL,
    RENT_DATE TIMESTAMP NOT NULL,
    BOOK_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    PRIMARY KEY(ID)
);