CREATE TABLE USERS(
    ID BIGINT IDENTITY PRIMARY KEY,
    FIRSTNAME VARCHAR(255) NOT NULL,
    LASTNAME VARCHAR(255) NOT NULL,
    USERNAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL
);

CREATE TABLE ROLES(
    ID BIGINT IDENTITY PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE USER_ROLES(
    USER_ID BIGINT NOT NULL REFERENCES USERS(ID) ,
    ROLE_iD BIGINT NOT NULL REFERENCES ROLES(ID)
);

CREATE TABLE BOOKS(
    ID BIGINT IDENTITY PRIMARY KEY,
    AUTHOR VARCHAR(255) NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    AVAILABLE_COPIES INTEGER NOT NULL,
    TOTAL_COPIES INTEGER NOT NULL
);

CREATE TABLE RENTS(
    ID BIGINT IDENTITY PRIMARY KEY,
    RENT_DATE TIMESTAMP NOT NULL,
    BOOK_ID BIGINT NOT NULL REFERENCES BOOKS(ID),
    USER_ID BIGINT NOT NULL REFERENCES USERS(ID)
);